name: TCCHub
options:
  bundleIdPrefix: kz.tcchub
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: "1"
    GENERATE_INFOPLIST_FILE: YES
    ENABLE_USER_SCRIPT_SANDBOXING: YES
targets:
  TCCHub:
    type: application
    platform: iOS
    sources:
      - path: TCCHub
    excludes:
      - "Design/**"
    info:
      path: TCCHub/Info.plist
      properties:
        CFBundleDisplayName: TCC Hub
        UILaunchScreen:
          UIColorName: ""
          UIImageName: "LogoFull"
          UIImageRespectsSafeAreaInsets: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        CFBundleLocalizations:
          - en
          - ru
          - kk
        CFBundleDevelopmentRegion: en
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true
          NSExceptionDomains:
            localhost:
              NSExceptionAllowsInsecureHTTPLoads: true
              NSIncludesSubdomains: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: kz.tcchub.lms
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
